services:
  init:
    image: busybox
    command: sh -c "mkdir -p /dbt_db && chmod 777 /dbt_db"
    volumes:
      - ./dbt_db:/dbt_db
    restart: "no"

  airflow:
    build:
      context: ./airflow
    image: local/airflow-spark-dbt:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__CORE__FERNET_KEY: "3AXuW2z8sfkvfOeixxG4JZ2tY5uxb62jTNvAItNljMQ="
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
      DBT_PROFILES_DIR: /opt/airflow/dbt
      PATH: /home/airflow/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      JAVA_TOOL_OPTIONS: "-XX:TieredStopAtLevel=1"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/data
      - ./warehouse:/warehouse
      - ./dbt:/opt/airflow/dbt
      - ./dbt_db:/opt/airflow/dbt_db
      - ./spark:/opt/spark
    ports:
      - 8080:8080
    entrypoint: ["/bin/bash", "/start.sh"]
    depends_on:
      init:
        condition: service_completed_successfully
      spark-master:
        condition: service_started
      spark-worker:
        condition: service_started

  spark-master:
    image: apache/spark:3.5.4
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - 7077:7077
      - 8081:8081
    volumes:
      - ./data:/data
      - ./warehouse:/warehouse

  spark-worker:
    image: apache/spark:3.5.4
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    volumes:
      - ./data:/data
      - ./warehouse:/warehouse

volumes:
  airflow_logs:
