version: 2

models:
  - name: stg_fraud
    description: "Staging model for raw fraud transactions loaded into Iceberg."
    columns:
      - name: timestamp
        tests:
          - not_null
      - name: sending_address
        tests:
          - not_null
      - name: receiving_address
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
